projects/angular-ui/src/lib/button/button.component.spec.ts, projects/angular-ui/src/lib/button/button.component.ts, projects/angular-ui/src/lib/button/tests/button.hostcomponent.spec.ts
also remove a warning in component.ts file. 
close #13
Signed-off-by: Olivier Albertini <olivier.albertini@montreal.ca>
=> test(button): add spec file for BaoButtonComponent

projects/angular-ui/src/lib/button/button.component.scss, projects/angular-ui/src/lib/checkbox/checkbox.component.scss, projects/angular-ui/src/lib/core/_colors.scss, projects/angular-ui/src/lib/radio/radio.component.scss, projects/angular-ui/src/lib/radio/radio.component.ts
=> fix: Update color for disabled element to tertiary color

package-lock.json, package.json, projects/angular-ui/package-lock.json, projects/angular-ui/package.json, projects/angular-ui/src/lib/core/colors.ts, projects/angular-ui/src/lib/shared/enum/display-mode.ts, projects/angular-ui/src/public-api.ts
Signed-off-by: TolaSam <tola.sam@montreal.ca>
=> feat: Export const and shared module

projects/angular-ui/src/lib/alert/alert.component.scss, projects/angular-ui/src/lib/icon/icon.component.scss, projects/angular-ui/src/lib/tag/tag.component.scss
Signed-off-by: Sorina Ardelean <sorina.ardelean@montreal.ca>
- fix display bao-icon in Safari
- close #29
=> fix: bao-icon display in safari

projects/angular-ui/src/lib/tag/tag.component.spec.ts, projects/angular-ui/src/lib/tag/tag.component.ts, projects/angular-ui/src/lib/tag/tests/tag.hostcomponent.spec.ts
remove warning from tag component. close #20
=> test(tag): add unit tests for BaoTagComponent

projects/angular-ui/src/lib/alert/alert.component.html, projects/angular-ui/src/lib/alert/alert.component.ts, projects/storybook-angular/src/stories/Alert/Alert.stories.ts
=> feat(alert): remove showIcon input to comply with accessibility rules.

projects/angular-ui/src/lib/alert/alert.component.ts, projects/storybook-angular/src/stories/Alert/Alert.stories.ts
=> feat(alert): remove empty type and change default type. close #30.

projects/angular-ui/src/lib/avatar/avatar.component.html, projects/angular-ui/src/lib/avatar/avatar.component.scss, projects/angular-ui/src/lib/avatar/avatar.component.spec.ts, projects/angular-ui/src/lib/avatar/avatar.component.ts, projects/angular-ui/src/lib/avatar/index.ts, projects/angular-ui/src/lib/avatar/module.ts, projects/angular-ui/src/lib/avatar/tests/avatar.hostcomponent.spec.ts, projects/angular-ui/src/lib/bao.module.ts, projects/angular-ui/src/public-api.ts, projects/storybook-angular/src/stories/Avatar/Avatar.stories.ts
=> feat(avatar): add bao-avatar component.

package-lock.json, projects/angular-ui/package-lock.json
Signed-off-by: TolaSam <tola.sam@montreal.ca>
=> Add version 3.1.0

Jenkinsfile
Signed-off-by: Olivier Albertini <olivier.albertini@montreal.ca>
=> ci(jenkins): fix build issue

projects/angular-ui/src/lib/bao.module.ts, projects/angular-ui/src/lib/hyperlink/hyperlink.component.html, projects/angular-ui/src/lib/hyperlink/hyperlink.component.scss, projects/angular-ui/src/lib/hyperlink/hyperlink.component.spec.ts, projects/angular-ui/src/lib/hyperlink/hyperlink.component.ts, projects/angular-ui/src/lib/hyperlink/index.ts, projects/angular-ui/src/lib/hyperlink/module.ts, projects/angular-ui/src/lib/hyperlink/tests/hyperlink.hostcomponent.spec.ts, projects/angular-ui/src/public-api.ts, projects/storybook-angular/src/stories/Hyperlink/Hyperlink.stories.ts
=> feat(hyperlink): add bao-hyperlink component. close #86

projects/angular-ui/global.scss, projects/angular-ui/src/lib/bao.module.ts, projects/angular-ui/src/lib/dropdown-menu/dropdown-menu.component.html, projects/angular-ui/src/lib/dropdown-menu/dropdown-menu.component.scss, projects/angular-ui/src/lib/dropdown-menu/dropdown-menu.component.spec.ts, projects/angular-ui/src/lib/dropdown-menu/dropdown-menu.component.ts, projects/angular-ui/src/lib/dropdown-menu/index.ts, projects/angular-ui/src/lib/dropdown-menu/module.ts, projects/angular-ui/src/lib/dropdown-menu/tests/dropdown-menu.hostcomponent.spec.ts, projects/angular-ui/src/public-api.ts, projects/storybook-angular/src/stories/DropdownMenu/DropdownMenu.stories.ts
=> feat(dropdown-menu): add dropdown-menu component. close #50

projects/angular-ui/RELEASING.md
for describing how to publish the library
close #104
Signed-off-by: Olivier Albertini <olivier.albertini@montreal.ca>
=> docs: add releasing file

projects/angular-ui/src/lib/bao.module.ts, projects/angular-ui/src/lib/common-components/label-text/labelText.component.scss, projects/angular-ui/src/lib/common-components/label-text/labelText.component.ts, projects/angular-ui/src/lib/common-components/module.ts, projects/angular-ui/src/lib/core/_typography.scss, projects/angular-ui/src/lib/dropdown-menu/dropdown-menu.component.ts, projects/angular-ui/src/lib/file/file-input.component.html, projects/angular-ui/src/lib/file/file-input.component.scss, projects/angular-ui/src/lib/file/file-input.component.spec.ts, projects/angular-ui/src/lib/file/file-input.component.ts, projects/angular-ui/src/lib/file/file-intl.ts, projects/angular-ui/src/lib/file/file-preview.component.html, projects/angular-ui/src/lib/file/file-preview.component.scss, projects/angular-ui/src/lib/file/file-preview.component.spec.ts, projects/angular-ui/src/lib/file/file-preview.component.ts, projects/angular-ui/src/lib/file/index.ts, projects/angular-ui/src/lib/file/module.ts, projects/angular-ui/src/lib/file/tests/file-input.hostcomponent.spec.ts, projects/angular-ui/src/lib/file/tests/file-preview.hostcomponent.spec.ts, projects/angular-ui/src/public-api.ts, projects/storybook-angular-examples/src/app/file/file-example.component.html, projects/storybook-angular-examples/src/app/file/file-example.component.ts, projects/storybook-angular/src/stories/File/FileInput.stories.ts, projects/storybook-angular/src/stories/File/FilePreview.stories.ts
(cherry picked from commit 6e1256718a642fff6bb1c373151ae93adac76d52)
=> feat(file-input): add file-input component. close #88. (#110). For Angular 13

projects/angular-ui/src/lib/file/file-input.component.scss, projects/angular-ui/src/lib/file/file-input.component.ts, projects/angular-ui/src/lib/file/file-preview.component.scss
=> fix(file): remove unnecessary margin and fix error when no guiding test is provided. close #117.

package-lock.json, package.json, projects/angular-ui/package.json, projects/angular-ui/src/lib/bao.module.ts, projects/angular-ui/src/lib/modal/modal-container.ts, projects/angular-ui/src/lib/modal/modal-ref.ts, projects/angular-ui/src/lib/modal/modal.ts, projects/angular-ui/src/lib/modal/module.ts, projects/storybook-angular-examples/src/app/app.module.ts
Signed-off-by: TolaSam <tola.sam@montreal.ca>
=> Feat: Remove animation module

.gitignore, projects/angular-ui/src/lib/bao.module.ts, projects/angular-ui/src/lib/snack-bar/index.ts, projects/angular-ui/src/lib/snack-bar/module.ts, projects/angular-ui/src/lib/snack-bar/simple-snack-bar.component.html, projects/angular-ui/src/lib/snack-bar/simple-snack-bar.component.scss, projects/angular-ui/src/lib/snack-bar/simple-snack-bar.component.ts, projects/angular-ui/src/lib/snack-bar/snack-bar-config.ts, projects/angular-ui/src/lib/snack-bar/snack-bar-container.html, projects/angular-ui/src/lib/snack-bar/snack-bar-container.scss, projects/angular-ui/src/lib/snack-bar/snack-bar-container.ts, projects/angular-ui/src/lib/snack-bar/snack-bar-overlay.component.scss, projects/angular-ui/src/lib/snack-bar/snack-bar.ts, projects/angular-ui/src/public-api.ts, projects/storybook-angular-examples/src/app/snack-bar/module.ts, projects/storybook-angular-examples/src/app/snack-bar/snack-bar-preview/snack-bar-preview.component.ts, projects/storybook-angular-examples/src/app/snack-bar/snack-bar-preview/snack-bar-preview.html, projects/storybook-angular-examples/src/app/snack-bar/snack-bar-simple-with-action/snack-bar-simple-with-action-example.component.ts, projects/storybook-angular-examples/src/app/snack-bar/snack-bar-simple-with-action/snack-bar-simple-with-action-example.html, projects/storybook-angular-examples/src/app/snack-bar/snack-bar-simple-with-config/snack-bar-simple-with-config-example.component.ts, projects/storybook-angular-examples/src/app/snack-bar/snack-bar-simple-with-config/snack-bar-simple-with-config-example.html, projects/storybook-angular-examples/src/app/snack-bar/snack-bar-simple/snack-bar-simple-example.component.ts, projects/storybook-angular-examples/src/app/snack-bar/snack-bar-simple/snack-bar-simple-example.html, projects/storybook-angular/src/stories/Modal/Modal.stories.ts, projects/storybook-angular/src/stories/SnackBar/SnackBar.stories.ts
* feat: #54 reintroduce the snackbar
Signed-off-by: Matthieu <matthieu.perrin@montreal.ca>
* fix: code review changes
Signed-off-by: Matthieu <matthieu.perrin@montreal.ca>
=> feat: #54 reintroduce the snackbar (#151)

projects/angular-ui/src/lib/breadcrumb/breadcrumb.component.html, projects/angular-ui/src/lib/breadcrumb/breadcrumb.component.scss, projects/angular-ui/src/lib/breadcrumb/breadcrumb.component.spec.ts, projects/angular-ui/src/lib/breadcrumb/breadcrumb.component.ts
Update breadcrumb structure :
```
<bao-breadcrumb>
<nav aria-label=”Fil d’ariane”>
<ol>
<li>
<a [routerLink]="page1">Page 1</a>
</li>
<li>
<a [routerLink]="page2">Page 2</a>
</li>
<li>
<a [routerLink]="page3">Page 3</a>
</li>
</ol>
</nav>
</bao-breadcrumb>
```
=> add list elements to follow accessibility rules

CONTRIBUTING.md, CONTRIBUTING_FR.md, README.md, README_FR.md, RELEASING.md
also adding english version like other repos
close #21
=> docs: updating readme

RELEASING.md
The order of the batch commands for releasing was inverted
=> doc: update RELEASING commands order

projects/angular-ui/src/lib/system-header/system-header.component.ts
https://netbasal.com/a-new-way-to-set-inputs-on-angular-componentrefs-6214f95db63d
=> fix: fix the build, setInput() introduced in angular 15

projects/angular-ui/src/lib/alert/alert.component.scss
=> Feature: bao-alert icon svg fix

projects/angular-ui/src/lib/alert/alert.component.html, projects/angular-ui/src/lib/alert/alert.component.spec.ts, projects/angular-ui/src/lib/alert/alert.component.ts, projects/angular-ui/src/lib/icon/icon.component.ts, projects/storybook-angular/src/stories/Alert/Alert.stories.ts
=> fix: Issue-63 : Add the possibility to override Alert texts

projects/angular-ui/src/lib/file/file-preview.component.html, projects/angular-ui/src/lib/file/file-preview.component.ts
- use setter that triggers getThumbnail() and setIcon() every time the file input changes.
- remove the file size getter and use the abovementioned fix to improve performance
=> fix: force refresh thumbnail and performance improvement

projects/angular-ui/src/lib/button/button.component.ts
fix: replace ngAfterViewInit by ngAfterContentInit
=> fix: ExpressionChangedAfterItHasBeenCheckedError (#182)

projects/angular-ui/src/lib/dropdown-menu/dropdown-menu.component.scss, projects/angular-ui/src/lib/dropdown-menu/dropdown-menu.component.ts, projects/angular-ui/src/lib/list/list-item.component.html, projects/angular-ui/src/lib/list/list.component.scss, projects/angular-ui/src/lib/list/list.component.spec.ts, projects/angular-ui/src/lib/list/tests/list.hostcomponent.spec.ts, projects/storybook-angular/src/stories/List/List.stories.ts
=> feat: crmmon-7566 - Add a dropdown menu as a list item option

projects/angular-ui/src/lib/file/file-preview.component.ts
https://github.com/user-attachments/assets/84e08619-9a62-457d-b119-9d45fae56cf1
=> fix: fixed errors in file preview
